In [106]:
#Load the environment variables
from dotenv import load_dotenv
load_dotenv()

True

In [107]:
### LLM
from langchain_groq import ChatGroq

llm = ChatGroq(
    model = "openai/gpt-oss-safeguard-20b"
)

llm.invoke("What is Langchain? in a single sentence").content.strip()

'LangChain is an open‑source framework that streamlines building applications powered by large language models by providing modular components for prompt construction, memory, and integration with external tools and APIs.'

#### **Load the Hospital Documents**

In [108]:
## Validate the path
import os
path ="../../Hospital_RAG_documents"

if os.path.exists(path):
    print("Path is Valid")
else:
    print("Path is not Valid")

Path is Valid

In [109]:
### Document Loader
from langchain_community.document_loaders import DirectoryLoader,TextLoader

loader = DirectoryLoader(
    path,
    glob = "*.md",
    loader_cls = TextLoader,
    loader_kwargs={"encoding":"utf-8"}
)

documents = loader.load()

print("Number Of Documents:",len(documents))

Number Of Documents: 4

#### **Split the documents using Semantic Chunking**

In [110]:
### Embedding Model
### Create a Embedding model by HuggingFace with 1024 dimensions
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
        model = "BAAI/bge-large-en-v1.5",
        model_kwargs = {"device":"cpu"},
        encode_kwargs = {"normalize_embeddings":True}
)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

### ***Semantic Chunking means split the data based on semantic meaning instead of chunk_size***

In [111]:
from langchain_experimental.text_splitter import SemanticChunker

splitter= SemanticChunker(
    breakpoint_threshold_type = "percentile",
    breakpoint_threshold_amount = 90,
    embeddings=embedding_model
)

#### **Rechunking**

In [112]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

recursive_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 400,
    chunk_overlap = 60
)

In [113]:
chunks = recursive_splitter.split_documents(documents)
chunks

[Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='# ABC General Hospital — Departments\n\n## Department Overview\n\nABC General Hospital has several clinical departments.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='| Department | Main Area | Typical Services |\n|---|---|---|\n| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |\n| Neurology | Brain and nervous system | Neurological evaluation and care |\n| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |\n| Pediatrics | Children and adolescents | Pediatric consultations and care |'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='| Dermatology | Skin, hair, and nails | Dermatological evaluation and care |\n| General Medicine | General adult healthcare | General medical evaluation and management |'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='## Cardiology\n\nThe Cardiology Department focuses on evaluation and management of cardiovascular conditions.\n\n## Neurology\n\nThe Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.\n\n## Orthopedics\n\nThe Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='## Pediatrics\n\nThe Pediatrics Department provides healthcare services for children and adolescents.\n\n## Dermatology\n\nThe Dermatology Department focuses on conditions affecting the skin, hair, and nails.\n\n## General Medicine\n\nThe General Medicine Department provides general medical evaluation and management for adult patients.\n\n## Important Note'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='## Important Note\n\nThis is fictional hospital information created for a LangChain RAG project. It is not clinical guidance.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='# ABC General Hospital — Hospital Information\n\n## Overview\n\nABC General Hospital is a fictional hospital created for the Hospital RAG learning project. The hospital provides outpatient, inpatient, emergency, diagnostic, and specialist services.\n\n## Services\n\nThe hospital provides:'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='## Services\n\nThe hospital provides:\n\n- Outpatient consultations\n- Inpatient care\n- Emergency services\n- Diagnostic laboratory services\n- Radiology and imaging\n- Pharmacy services\n- Physiotherapy\n- Preventive health consultations\n\n## Emergency Services\n\nThe Emergency Department operates 24 hours a day, 7 days a week.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='Patients with urgent medical conditions should report to the Emergency Department. Emergency cases are prioritized according to clinical urgency.\n\n## Outpatient Services\n\nOutpatient consultations are available during scheduled department hours. Patients should register before their consultation unless they are receiving emergency care.\n\n## Diagnostic Services'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='## Diagnostic Services\n\nThe hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.\n\n## Pharmacy\n\nThe hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.\n\n## Important Note'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='## Important Note\n\nABC General Hospital is a fictional organization created only for learning and RAG experimentation. It is not a real hospital and this document does not provide medical advice.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\patient_guidelines.md'}, page_content='# ABC General Hospital — Patient Guidelines\n\n## Registration\n\nPatients should complete registration before receiving scheduled outpatient services.\n\nPatients may be asked to provide:\n\n- Identification information\n- Appointment information\n- Relevant medical information\n- Insurance information, when applicable\n\n## Appointments'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\patient_guidelines.md'}, page_content='## Appointments\n\nPatients with scheduled appointments should arrive before their appointment time to allow sufficient time for registration.\n\nAppointment availability depends on the relevant department and healthcare provider.\n\n## Emergency Care\n\nPatients requiring urgent care should report to the Emergency Department.\n\nEmergency services operate 24 hours a day, 7 days a week.\n\n## Visitors'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\patient_guidelines.md'}, page_content="## Visitors\n\nVisitors should follow the hospital's visiting schedule and instructions from hospital staff.\n\nVisitors should maintain a quiet environment and avoid interfering with medical care.\n\n## Patient Safety\n\nPatients should provide accurate information about their medical history, current medications, allergies, and other relevant information to healthcare professionals.\n\n## Documents"),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\patient_guidelines.md'}, page_content='## Documents\n\nDepending on the service, patients may be asked to provide identification, appointment details, insurance information, or previous medical records.\n\n## General Guidance\n\nPatients should follow instructions provided by qualified healthcare professionals regarding diagnosis, treatment, medication, and follow-up care.\n\n## Important Note'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\patient_guidelines.md'}, page_content='## Important Note\n\nABC General Hospital is fictional. These guidelines are created only for a LangChain RAG learning project and should not be treated as real medical or hospital policy.'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='# ABC General Hospital — Visiting Hours\n\n## General Visiting Schedule\n\n| Area | Visiting Hours | Days |\n|---|---|---|\n| General Ward | 10:00 AM - 12:00 PM | Monday - Sunday |\n| General Ward | 4:00 PM - 6:00 PM | Monday - Sunday |\n| ICU | 2:00 PM - 3:00 PM | Monday - Sunday |\n| Pediatrics | 4:00 PM - 6:00 PM | Monday - Saturday |\n| Outpatient Department | 9:00 AM - 1:00 PM | Monday - Saturday |'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='## General Ward\n\nVisitors may visit patients in the General Ward during the scheduled visiting periods.\n\n## Intensive Care Unit (ICU)\n\nICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.\n\n## Pediatrics\n\nPediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.\n\n## Outpatient Department'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='## Outpatient Department\n\nThe Outpatient Department operates from 9:00 AM to 1:00 PM, Monday through Saturday.\n\n## Visitor Guidelines\n\n- Visitors should follow hospital staff instructions.\n- Visiting conditions may be changed for operational or safety reasons.\n- Visitors should avoid disturbing patients or clinical activities.\n\n## Important Note'),
 Document(metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='## Important Note\n\nThese visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.')]

In [114]:
### Number of chunks
len(chunks)

20

#### ***Store in Chroma***

In [115]:
from langchain_chroma import Chroma

vectorstore = Chroma.from_documents(
    chunks,
    embedding=embedding_model,
    persist_directory="../../vectorstore/hospital_rag",
    collection_name="hospital_rag"
)

In [116]:
query = "What services are available in the Cardiology Department?"

In [117]:
query_vector = embedding_model.embed_query(query)
print(len(query_vector))

1024

#### **Create and test the retriever**

In [182]:
vector_retriever = vectorstore.as_retriever(search_type = "similarity",search_kwargs = {"k":5})
retrieved_docs = vector_retriever.invoke(query)
retrieved_docs

[Document(id='ae9fcc8c-be56-45c8-8963-19ee749211d9', metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='## Important Note\n\nThese visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.'),
 Document(id='2c226fd9-2135-44bf-8f4e-c2d980530b43', metadata={'source': '..\\..\\Hospital_RAG_documents\\visiting_hours.md'}, page_content='## Important Note\n\nThese visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.'),
 Document(id='59235a2c-4313-4a8e-8938-5b65941825d9', metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='## Important Note\n\nThis is fictional hospital information created for a LangChain RAG project. It is not clinical guidance.'),
 Document(id='4c9ed752-23f1-4769-9bbf-2641d5d89c25', metadata={'source': '..\\..\\Hospital_RAG_documents\\departments.md'}, page_content='## Important Note\n\nThis is fictional hospital information created for a LangChain RAG project. It is not clinical guidance.'),
 Document(id='03fc7751-eb5c-4536-bac7-aa30c2a39542', metadata={'source': '..\\..\\Hospital_RAG_documents\\hospital_information.md'}, page_content='Patients with urgent medical conditions should report to the Emergency Department. Emergency cases are prioritized according to clinical urgency.\n\n## Outpatient Services\n\nOutpatient consultations are available during scheduled department hours. Patients should register before their consultation unless they are receiving emergency care.\n\n## Diagnostic Services')]

In [183]:
def format_docs(documents):

    return "\n\n".join(doc.page_content for doc in documents)

In [184]:
# design a prompt
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""
You are a Kubernetes documentation Assistant.

Answer the question using only the provided Context only.


Rules:
    1.Don't use information outside the Context.
    2.If the answer is not available in the context,
    say I don't have information based on the Provided Documents.

Context:
{context}

Question:
{question}

Answer:
""")

#### ***Step 6 — Build the RAG flow***

In [185]:
### Vector similarity search
def rag(query):

    retrieved_docs  =  vector_retriever.invoke(query)
    

    context = format_docs(retrieved_docs)

    message = prompt.invoke({"context":context,"question":query})

    response = llm.invoke(message).content

    return response

In [122]:
answer = rag(query)
print(answer)

Cardiology offers cardiac evaluation and cardiovascular care.

#### ***BM25 Retriver***

In [123]:
from langchain_classic.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(chunks)

In [186]:
bm25_retriever.k=5

#### ***Hybrid Search = Vector + BM25 Retriever***

In [187]:
from langchain_classic.retrievers import EnsembleRetriever

hybrid_retriever = EnsembleRetriever(
    retrievers=[vector_retriever,bm25_retriever],
    weights= [0.7,0.3]
)

In [188]:

def hybrid_rag(query):

    retrieved_docs  =  hybrid_retriever.invoke(query)
    

    context = format_docs(retrieved_docs)

    message = prompt.invoke({"context":context,"question":query})

    response = llm.invoke(message).content

    return response

In [189]:
answer = rag(query)
print(answer)

I don't have information based on the Provided Documents.

In [191]:
print("What are the visiting hours for the ICU?")
vector_response = rag("What are the visiting hours for the ICU?")
hybrid_response = hybrid_rag("What are the visiting hours for the ICU?")
print("Vector Response:",vector_response)
print("Hybrid Response:",hybrid_response)

What are the visiting hours for the ICU?
Vector Response: The ICU visiting hours are **2:00 PM to 3:00 PM, Monday through Sunday**.
Hybrid Response: The ICU visiting hours are **2:00 PM to 3:00 PM, Monday through Sunday**.

#### ***Step 7 — Add the Patient-Data Tool***

In [192]:
import pandas as pd

In [130]:
patients_df = pd.read_csv("../../Data/patients.csv")
patients_df[:5]

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,cc3eac4a-34a7-9a15-1522-8087135631b7,1978-01-16,NaN,999-55-9547,S99974479,X81842955X,Mr.,Guillermo498,NaN,VonRueden376,...,North Brookfield,Massachusetts,Worcester County,25027.0,1535,42.267480,-72.105242,104532.20,18048.65,42283
1,8b9df7af-24b3-66ee-afeb-2734ebcbd33c,2001-02-11,NaN,999-32-1995,S99911042,X98255942X,Ms.,Jayne73,Mira443,Bruen238,...,Bedford,Massachusetts,Middlesex County,25017.0,1730,42.539821,-71.256841,98009.84,531508.43,33657
2,65cbad6a-eb9d-420e-9bab-b4f9c6aab7db,1948-06-15,NaN,999-23-9791,S99928100,X83081075X,Mrs.,Grisel924,Dortha70,Balistreri607,...,Quincy,Massachusetts,Norfolk County,25021.0,2170,42.204748,-70.988341,796732.91,219824.56,64779
3,9a3814bb-f5b0-05f3-928e-fe6640d5aa2a,2015-07-19,NaN,999-56-4831,NaN,NaN,NaN,Esperanza675,Rachell479,Auer97,...,Taunton,Massachusetts,Bristol County,25005.0,2718,41.902707,-70.976300,44050.63,17747.77,34422
4,6a703775-432b-ba7d-d53a-c4d7bb0f5b58,1995-01-23,NaN,999-91-2539,S99931120,X52632004X,Mr.,Arnulfo253,NaN,Boyer713,...,Boston,Massachusetts,Suffolk County,25025.0,2116,42.359644,-71.079948,5450.00,97459.94,6565

In [131]:
patients_df.columns

Index(['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX',
       'FIRST', 'MIDDLE', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE',
       'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE',
       'COUNTY', 'FIPS', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES',
       'HEALTHCARE_COVERAGE', 'INCOME'],
      dtype='str')

In [132]:
patients_df.head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,cc3eac4a-34a7-9a15-1522-8087135631b7,1978-01-16,NaN,999-55-9547,S99974479,X81842955X,Mr.,Guillermo498,NaN,VonRueden376,...,North Brookfield,Massachusetts,Worcester County,25027.0,1535,42.267480,-72.105242,104532.20,18048.65,42283
1,8b9df7af-24b3-66ee-afeb-2734ebcbd33c,2001-02-11,NaN,999-32-1995,S99911042,X98255942X,Ms.,Jayne73,Mira443,Bruen238,...,Bedford,Massachusetts,Middlesex County,25017.0,1730,42.539821,-71.256841,98009.84,531508.43,33657
2,65cbad6a-eb9d-420e-9bab-b4f9c6aab7db,1948-06-15,NaN,999-23-9791,S99928100,X83081075X,Mrs.,Grisel924,Dortha70,Balistreri607,...,Quincy,Massachusetts,Norfolk County,25021.0,2170,42.204748,-70.988341,796732.91,219824.56,64779
3,9a3814bb-f5b0-05f3-928e-fe6640d5aa2a,2015-07-19,NaN,999-56-4831,NaN,NaN,NaN,Esperanza675,Rachell479,Auer97,...,Taunton,Massachusetts,Bristol County,25005.0,2718,41.902707,-70.976300,44050.63,17747.77,34422
4,6a703775-432b-ba7d-d53a-c4d7bb0f5b58,1995-01-23,NaN,999-91-2539,S99931120,X52632004X,Mr.,Arnulfo253,NaN,Boyer713,...,Boston,Massachusetts,Suffolk County,25025.0,2116,42.359644,-71.079948,5450.00,97459.94,6565

In [133]:
patients_df.shape

(108, 28)

In [134]:
patient_columns = [
    "Id",
    "PREFIX",
    "FIRST",
    "MIDDLE",
    "LAST",
    "SUFFIX",
    "BIRTHDATE",
    "GENDER",
    "MARITAL",
    "BIRTHPLACE",
    "CITY",
    "STATE",
    "ZIP",
    "HEALTHCARE_EXPENSES",
    "HEALTHCARE_COVERAGE",
    "INCOME"
]

patients_df = patients_df[patient_columns].copy()

In [135]:
patients_df['Id'][:5]

0    cc3eac4a-34a7-9a15-1522-8087135631b7
1    8b9df7af-24b3-66ee-afeb-2734ebcbd33c
2    65cbad6a-eb9d-420e-9bab-b4f9c6aab7db
3    9a3814bb-f5b0-05f3-928e-fe6640d5aa2a
4    6a703775-432b-ba7d-d53a-c4d7bb0f5b58
Name: Id, dtype: str

In [136]:
name_columns = ["PREFIX", "FIRST", "MIDDLE", "LAST", "SUFFIX"]

patients_df["Name"] = (
    patients_df[name_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [137]:
patients_df = patients_df.drop(columns=name_columns)

In [193]:
from langchain_core.tools import tool

@tool
def search_patient(patient_id):

    """Search the hospital's synthetic patient records using a patient ID
     and return the matching patient information."""

    patient = patients_df[patients_df["Id"]==patient_id]

    if patient.empty:
        return "Patient not found"

    return patient.to_dict(orient = "records")[0]

In [194]:
search_patient.invoke("9a3814bb-f5b0-05f3-928e-fe6640d5aa2a")

{'Id': '9a3814bb-f5b0-05f3-928e-fe6640d5aa2a',
 'BIRTHDATE': '2015-07-19',
 'GENDER': 'F',
 'MARITAL': nan,
 'BIRTHPLACE': 'Stoughton  Massachusetts  US',
 'CITY': 'Taunton',
 'STATE': 'Massachusetts',
 'ZIP': 2718,
 'HEALTHCARE_EXPENSES': 44050.63,
 'HEALTHCARE_COVERAGE': 17747.77,
 'INCOME': 34422,
 'Name': 'Esperanza675 Rachell479 Auer97'}

#### **Reranking**

In [195]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2"
)

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

In [201]:
@tool
def hospital_search(query: str):
    """Search the hospital knowledge base and answer questions using information retrieved from the hospital documents."""
    
    retrieved_docs = hybrid_retriever.invoke(query)

    pairs = [[query,doc.page_content] for doc in retrieved_docs]

    scores = reranker.predict(pairs)

    ranked_docs = sorted(zip(retrieved_docs,scores), key = lambda x:x[1],reverse=True)

    top_docs = [doc for doc,score in ranked_docs[:3]]



    context = format_docs(top_docs)

    message = prompt.invoke({
        "context": context,
        "question": query
    })

    response = llm.invoke(message).content

    return response

In [141]:
hospital_search.invoke({
    "query": "What are the ICU visiting hours?"
})

--- Document 1 ---
## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods.

## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.

## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.

## Outpatient Department

--- Document 2 ---
# ABC General Hospital — Visiting Hours

## General Visiting Schedule

| Area | Visiting Hours | Days |
|---|---|---|
| General Ward | 10:00 AM - 12:00 PM | Monday - Sunday |
| General Ward | 4:00 PM - 6:00 PM | Monday - Sunday |
| ICU | 2:00 PM - 3:00 PM | Monday - Sunday |
| Pediatrics | 4:00 PM - 6:00 PM | Monday - Saturday |
| Outpatient Department | 9:00 AM - 1:00 PM | Monday - Saturday |

## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods. ## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff. ## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday. ## Outpatient Department

The Outpatient Department operates from 9:00 AM to 1:00 PM, Monday through Saturday. ## Visitor Guidelines

- Visitors should follow hospital staff instructions.

--- Document 3 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.

--- Document 4 ---
Patients with urgent medical conditions should report to the Emergency Department. Emergency cases are prioritized according to clinical urgency.

## Outpatient Services

Outpatient consultations are available during scheduled department hours. Patients should register before their consultation unless they are receiving emergency care.

## Diagnostic Services

'ICU visiting hours are 2:00\u202fPM to 3:00\u202fPM, Monday through Sunday.'

In [142]:
hospital_search.invoke({
    "query": "What services are available in the Cardiology Department?"
})

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
Patients with urgent medical conditions should report to the Emergency Department. Emergency cases are prioritized according to clinical urgency.

## Outpatient Services

Outpatient consultations are available during scheduled department hours. Patients should register before their consultation unless they are receiving emergency care.

## Diagnostic Services

--- Document 4 ---
## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods.

## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.

## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.

## Outpatient Department

'Cardiology provides cardiac evaluation and cardiovascular care, focusing on the evaluation and management of cardiovascular conditions.'

In [202]:
tools = [
    hospital_search,
    search_patient
]

In [203]:
llm_with_tools = llm.bind_tools(tools)

In [204]:
tool_map = {tool.name:tool for tool in tools}
tool_map

{'hospital_search': StructuredTool(name='hospital_search', description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.', args_schema=<class 'langchain_core.utils.pydantic.hospital_search'>, func=<function hospital_search at 0x000001D2F1180400>),
 'search_patient': StructuredTool(name='search_patient', description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information.", args_schema=<class 'langchain_core.utils.pydantic.search_patient'>, func=<function search_patient at 0x000001D2F116AF20>)}

In [205]:
llm_with_tools.invoke("What are the ICU visiting hours?")

AIMessage(content='', additional_kwargs={'reasoning_content': 'User asks about ICU visiting hours. We need to search hospital knowledge base. Use hospital_search with query "ICU visiting hours".', 'tool_calls': [{'id': 'fc_06e32047-8111-4f9d-828a-e40dc9b4a887', 'function': {'arguments': '{"query":"ICU visiting hours"}', 'name': 'hospital_search'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 54, 'prompt_tokens': 173, 'total_tokens': 227, 'completion_time': 0.05439957, 'completion_tokens_details': {'reasoning_tokens': 27}, 'prompt_time': 0.009692284, 'prompt_tokens_details': None, 'queue_time': 0.048400566, 'total_time': 0.064091854}, 'model_name': 'openai/gpt-oss-safeguard-20b', 'system_fingerprint': 'fp_b5ae46a825', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--01a04194-d4a3-7400-849d-3e262a379aec-0', tool_calls=[{'name': 'hospital_search', 'args': {'query': 'ICU visiting hours'}, 'id': 'fc_06e32047-8111-4f9d-828a-e40dc9b4a887', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 173, 'output_tokens': 54, 'total_tokens': 227, 'output_token_details': {'reasoning': 27}})

In [147]:
from langchain_core.messages import HumanMessage,ToolMessage
query = "What are the ICU visiting hours?"

#### **Dynamic Tool Calling**

In [164]:
def tool_loop_execution(query):
    messages = [HumanMessage(query)]
    while True:

        response = llm_with_tools.invoke(messages)

        messages.append(response)

        if not response.tool_calls:
            break

        for tool_call in response.tool_calls:
            tool_name = tool_call['name']
            tool_args = tool_call['args']
            tool_id = tool_call['id']

            tool = tool_map[tool_name]
            result = tool.invoke(tool_args)
            print("Tool Name:",tool)
            messages.append(ToolMessage(content = str(result),tool_call_id = tool_id))
    return response

In [149]:
response = tool_loop_execution(query).content
print(response)

--- Document 1 ---
## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods.

## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.

## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.

## Outpatient Department

--- Document 2 ---
# ABC General Hospital — Visiting Hours

## General Visiting Schedule

| Area | Visiting Hours | Days |
|---|---|---|
| General Ward | 10:00 AM - 12:00 PM | Monday - Sunday |
| General Ward | 4:00 PM - 6:00 PM | Monday - Sunday |
| ICU | 2:00 PM - 3:00 PM | Monday - Sunday |
| Pediatrics | 4:00 PM - 6:00 PM | Monday - Saturday |
| Outpatient Department | 9:00 AM - 1:00 PM | Monday - Saturday |

## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods. ## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff. ## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday. ## Outpatient Department

The Outpatient Department operates from 9:00 AM to 1:00 PM, Monday through Saturday. ## Visitor Guidelines

- Visitors should follow hospital staff instructions.

--- Document 3 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.

--- Document 4 ---
## Visitors

Visitors should follow the hospital's visiting schedule and instructions from hospital staff.

Visitors should maintain a quiet environment and avoid interfering with medical care.

## Patient Safety

Patients should provide accurate information about their medical history, current medications, allergies, and other relevant information to healthcare professionals.

## Documents
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
The ICU visiting hours are **2:00 PM to 3:00 PM, Monday through Sunday**.

In [150]:
patient_ids = patients_df["Id"].head(3).tolist()
patient_ids

['cc3eac4a-34a7-9a15-1522-8087135631b7',
 '8b9df7af-24b3-66ee-afeb-2734ebcbd33c',
 '65cbad6a-eb9d-420e-9bab-b4f9c6aab7db']

In [151]:
vectorstore._collection.count()

50

#### ***Hospital/RAG***

In [152]:
hospital_queries = [
    "What are the ICU visiting hours?",
    "What services are available in the Cardiology Department?",
    "Which department provides care for children and adolescents?",
    "What services does the hospital provide?",
    "Does the hospital provide pharmacy services?",
    "What diagnostic services are available at the hospital?",
    "What departments are available at ABC General Hospital?"
]
for query in hospital_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What are the ICU visiting hours?

--- Document 1 ---
## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods.

## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.

## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.

## Outpatient Department

--- Document 2 ---
# ABC General Hospital — Visiting Hours

## General Visiting Schedule

| Area | Visiting Hours | Days |
|---|---|---|
| General Ward | 10:00 AM - 12:00 PM | Monday - Sunday |
| General Ward | 4:00 PM - 6:00 PM | Monday - Sunday |
| ICU | 2:00 PM - 3:00 PM | Monday - Sunday |
| Pediatrics | 4:00 PM - 6:00 PM | Monday - Saturday |
| Outpatient Department | 9:00 AM - 1:00 PM | Monday - Saturday |

## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods. ## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff. ## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday. ## Outpatient Department

The Outpatient Department operates from 9:00 AM to 1:00 PM, Monday through Saturday. ## Visitor Guidelines

- Visitors should follow hospital staff instructions.

--- Document 3 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.

--- Document 4 ---
## Visitors

Visitors should follow the hospital's visiting schedule and instructions from hospital staff.

Visitors should maintain a quiet environment and avoid interfering with medical care.

## Patient Safety

Patients should provide accurate information about their medical history, current medications, allergies, and other relevant information to healthcare professionals.

## Documents
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: The ICU visiting hours are **2:00 PM – 3:00 PM, Monday through Sunday**.
------------------------------------------------------------
Query: What services are available in the Cardiology Department?

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
# ABC General Hospital — Departments

## Department Overview

ABC General Hospital has several clinical departments. | Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |
| Dermatology | Skin, hair, and nails | Dermatological evaluation and care |
| General Medicine | General adult healthcare | General medical evaluation and management |

## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions. ## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions. ## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures. ## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents. ## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails. ## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients. ## Important Note

This is fictional hospital information created for a LangChain RAG project.

--- Document 4 ---
## Services

The hospital provides:

- Outpatient consultations
- Inpatient care
- Emergency services
- Diagnostic laboratory services
- Radiology and imaging
- Pharmacy services
- Physiotherapy
- Preventive health consultations

## Emergency Services

The Emergency Department operates 24 hours a day, 7 days a week.

--- Document 5 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: **Cardiology Department Services**

- **Cardiac Evaluation** – Comprehensive assessment of heart health, including history, physical exam, and diagnostic testing.
- **Cardiovascular Care** – Ongoing management and treatment of cardiovascular conditions, ranging from preventive care to advanced therapies.

If you need more specific details or want to schedule an appointment, let me know!
------------------------------------------------------------
Query: Which department provides care for children and adolescents?

--- Document 1 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
## Diagnostic Services

The hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.

## Pharmacy

The hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: The department that provides care for children and adolescents is **Pediatrics**.
------------------------------------------------------------
Query: What services does the hospital provide?

--- Document 1 ---
## Services

The hospital provides:

- Outpatient consultations
- Inpatient care
- Emergency services
- Diagnostic laboratory services
- Radiology and imaging
- Pharmacy services
- Physiotherapy
- Preventive health consultations

## Emergency Services

The Emergency Department operates 24 hours a day, 7 days a week.

--- Document 2 ---
## Diagnostic Services

The hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.

## Pharmacy

The hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.

## Important Note

--- Document 3 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: Our hospital offers a comprehensive range of services to meet the diverse needs of our patients:

| Category | Services |
|----------|----------|
| **Outpatient Care** | • General consultations<br>• Specialist clinics (e.g., cardiology, orthopedics, dermatology)<br>• Follow‑up visits |
| **Inpatient Care** | • General medicine and surgery wards<br>• Intensive Care Unit (ICU)<br>• Post‑operative care |
| **Emergency Services** | • 24/7 emergency department with rapid triage and treatment |
| **Diagnostic Laboratory** | • Blood tests, urine analysis, microbiology, pathology<br>• On‑site histopathology and cytology |
| **Radiology & Imaging** | • X‑ray, ultrasound, CT, MRI, and nuclear medicine<br>• Digital image storage and reporting |
| **Pharmacy** | • In‑house pharmacy with prescription dispensing and medication counselling |
| **Physiotherapy & Rehabilitation** | • In‑patient and outpatient physiotherapy<br>• Occupational therapy |
| **Preventive Health** | • Health screening programs (e.g., blood pressure, cholesterol, diabetes)<br>• Immunisation clinics |

If you’d like more detail on any specific department or service, just let me know!
------------------------------------------------------------
Query: Does the hospital provide pharmacy services?

--- Document 1 ---
## Diagnostic Services

The hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.

## Pharmacy

The hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.

## Important Note

--- Document 2 ---
## Services

The hospital provides:

- Outpatient consultations
- Inpatient care
- Emergency services
- Diagnostic laboratory services
- Radiology and imaging
- Pharmacy services
- Physiotherapy
- Preventive health consultations

## Emergency Services

The Emergency Department operates 24 hours a day, 7 days a week.

--- Document 3 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: Yes – the hospital operates an on‑site pharmacy that dispenses prescribed medications during its regular operating hours. Availability of specific drugs can vary, so it’s a good idea to confirm any particular medication needs with the pharmacy staff before you go.
------------------------------------------------------------
Query: What diagnostic services are available at the hospital?

--- Document 1 ---
## Diagnostic Services

The hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.

## Pharmacy

The hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.

## Important Note

--- Document 2 ---
## Services

The hospital provides:

- Outpatient consultations
- Inpatient care
- Emergency services
- Diagnostic laboratory services
- Radiology and imaging
- Pharmacy services
- Physiotherapy
- Preventive health consultations

## Emergency Services

The Emergency Department operates 24 hours a day, 7 days a week.

--- Document 3 ---
Patients with urgent medical conditions should report to the Emergency Department. Emergency cases are prioritized according to clinical urgency.

## Outpatient Services

Outpatient consultations are available during scheduled department hours. Patients should register before their consultation unless they are receiving emergency care.

## Diagnostic Services
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: **Diagnostic services available at the hospital**

| Category | Services offered |
|----------|-------------------|
| **Laboratory / Clinical Pathology** | • Blood tests (CBC, chemistry panels, coagulation, electrolytes, etc.)<br>• Microbiology (culture & sensitivity, rapid tests, etc.)<br>• Histopathology & cytology<br>• Molecular diagnostics (PCR, genetic testing)<br>• Urine & other body fluid analysis<br>• Special tests (e.g., HIV, hepatitis, blood typing) |
| **Radiology & Imaging** | • X‑ray (chest, limb, pelvis, etc.)<br>• Ultrasound (abdominal, pelvic, obstetric, vascular, cardiac)<br>• Computed Tomography (CT) scans<br>• Magnetic Resonance Imaging (MRI)<br>• Mammography & breast imaging<br>• Nuclear medicine (bone scans, PET/CT, SPECT)<br>• Interventional radiology (angiography, biopsies, drainages) |
| **Other Diagnostic Modalities** | • Electrocardiography (ECG/EKG)<br>• Cardiac stress testing<br>• Pulmonary function tests (PFTs)<br>• Electroencephalography (EEG)<br>• Ophthalmic diagnostics (visual acuity, slit‑lamp, OCT)<br>• Audiology (hearing tests) |

All these services are performed by trained specialists using state‑of‑the‑art equipment, ensuring accurate, timely results for patient care.
------------------------------------------------------------
Query: What departments are available at ABC General Hospital?

--- Document 1 ---
# ABC General Hospital — Departments

## Department Overview

ABC General Hospital has several clinical departments.

--- Document 2 ---
# ABC General Hospital — Departments

## Department Overview

ABC General Hospital has several clinical departments. | Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |
| Dermatology | Skin, hair, and nails | Dermatological evaluation and care |
| General Medicine | General adult healthcare | General medical evaluation and management |

## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions. ## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions. ## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures. ## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents. ## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails. ## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients. ## Important Note

This is fictional hospital information created for a LangChain RAG project.

--- Document 3 ---
# ABC General Hospital — Hospital Information

## Overview

ABC General Hospital is a fictional hospital created for the Hospital RAG learning project. The hospital provides outpatient, inpatient, emergency, diagnostic, and specialist services.

## Services

The hospital provides:

--- Document 4 ---
## Important Note

ABC General Hospital is fictional. These guidelines are created only for a LangChain RAG learning project and should not be treated as real medical or hospital policy.
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: ABC General Hospital offers a range of clinical departments, including:

- **Cardiology**
- **Neurology**
- **Orthopedics**
- **Pediatrics**
- **Dermatology**
- **General Medicine**
------------------------------------------------------------

#### ***Patient Data***

In [153]:
patient_queries = [
    "What is the gender of patient cc3eac4a-34a7-9a15-1522-8087135631b7?",
    "What is the birth date of patient 8b9df7af-24b3-66ee-afeb-2734ebcbd33c?",
    "What city does patient 65cbad6a-eb9d-420e-9bab-b4f9c6aab7db live in?",
    "What is the healthcare coverage of patient 8b9df7af-24b3-66ee-afeb-2734ebcbd33c?",
    "Give me the complete information for patient cc3eac4a-34a7-9a15-1522-8087135631b7?"
]
for query in patient_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What is the gender of patient cc3eac4a-34a7-9a15-1522-8087135631b7?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>
Response: The patient’s gender is **male** (M).
------------------------------------------------------------
Query: What is the birth date of patient 8b9df7af-24b3-66ee-afeb-2734ebcbd33c?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>
Response: The patient’s birth date is **February 11, 2001**.
------------------------------------------------------------
Query: What city does patient 65cbad6a-eb9d-420e-9bab-b4f9c6aab7db live in?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>
Response: The patient lives in **Quincy**.
------------------------------------------------------------
Query: What is the healthcare coverage of patient 8b9df7af-24b3-66ee-afeb-2734ebcbd33c?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>
Response: The patient’s healthcare coverage is **$531,508.43**.
------------------------------------------------------------
Query: Give me the complete information for patient cc3eac4a-34a7-9a15-1522-8087135631b7?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>
Response: **Patient Record – cc3eac4a-34a7-9a15-1522-8087135631b7**

| Field | Value |
|-------|-------|
| **ID** | cc3eac4a-34a7-9a15-1522-8087135631b7 |
| **Name** | Mr. Guillermo498 VonRueden376 MD |
| **Birthdate** | 1978‑01‑16 |
| **Gender** | Male |
| **Marital Status** | Divorced |
| **Birthplace** | Salem, Massachusetts, USA |
| **City of Residence** | North Brookfield |
| **State** | Massachusetts |
| **ZIP Code** | 1535 |
| **Healthcare Expenses** | $104,532.20 |
| **Healthcare Coverage** | $18,048.65 |
| **Annual Income** | $42,283 |

*Note: All values are pulled directly from the hospital’s synthetic patient database.*
------------------------------------------------------------

#### ***Direct/No Tool***

In [154]:
direct_queries = [
    "What is LangChain?",
    "What is the difference between RAG and fine-tuning?",
    "What is an embedding?",
    "What is cosine similarity?"
]
for query in direct_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What is LangChain?
Response: **LangChain** is an open‑source framework designed to help developers build applications that combine large language models (LLMs) with other tools, data sources, and external services. It abstracts away many of the low‑level details involved in creating “chain”‑based workflows where a language model can:

1. **Retrieve** information from external sources (e.g., databases, APIs, files).
2. **Process** that information using prompts or custom logic.
3. **Return** refined outputs or trigger subsequent actions.

Key concepts in LangChain:

- **Chains**: Sequential or conditional steps that involve LLM calls, function calls, or other operations.
- **Agents**: LLM-driven decision engines that can pick which tool to use based on a prompt.
- **Prompt Templates**: Reusable prompt structures that can be filled with dynamic data.
- **Memory**: Contextual state that can be stored and passed between steps.
- **Tool Integration**: Plug‑in interfaces for APIs, databases, web scraping, etc.

LangChain is popular in building chatbots, knowledge‑base assistants, data‑analysis pipelines, and other AI‑powered applications that require more than just a single “generate text” call. It’s maintained by the LangChain community and is built on top of major LLM providers like OpenAI, Anthropic, and others.
------------------------------------------------------------
Query: What is the difference between RAG and fine-tuning?
Response: **Retrieval‑Augmented Generation (RAG) vs. Fine‑Tuning**

| Feature | Retrieval‑Augmented Generation (RAG) | Fine‑Tuning |
|---------|-------------------------------------|-------------|
| **What it does** | Combines a pre‑trained language model with an external knowledge source (e.g., a vector store, database, or search engine). The model first retrieves the most relevant documents or snippets, then conditions its generation on that evidence. | Modifies the weights of the language model by training it on a new, domain‑specific dataset. The model learns to produce outputs that reflect the patterns in that data. |
| **When you need it** | • You want to keep the base model’s general knowledge but inject up‑to‑date, specialized facts.<br>• You have a large knowledge base that changes frequently (e.g., medical guidelines, product catalogs).<br>• You want to avoid re‑training the model from scratch. | • You have a large, high‑quality labeled dataset for a specific task or domain.<br>• You want the model to behave consistently across all inputs, not just when a retrieval step is invoked.<br>• You need the model to generalize within a narrow scope (e.g., a specific diagnostic pathway). |
| **How it works** | 1. **Retrieve**: Query a vector index or search engine with the user’s prompt. 2. **Fuse**: Feed the retrieved passages (or their embeddings) into the language model as additional context. 3. **Generate**: Produce the final answer using both the prompt and the evidence. | 1. **Dataset**: Compile a corpus of text or labeled examples.<br>2. **Training**: Run gradient descent on the model’s parameters, adjusting weights to minimize loss on the new data.<br>3. **Deployment**: Use the fine‑tuned model directly, without a separate retrieval step. |
| **Pros** | • **Fast adaptation**: Add new documents on the fly—no re‑training.<br>• **Scalable**: Works with very large knowledge bases; only a handful of passages are retrieved per query.<br>• **Explainability**: You can show the retrieved evidence that influenced the answer.<br>• **Safety**: Keeps the base model’s safeguards intact while still providing up‑to‑date facts. | • **Consistent behavior**: The model learns the domain patterns internally; no need to fetch documents each time.<br>• **Performance**: Often yields higher accuracy on specialized tasks because the model has internalized the knowledge.<br>• **No latency**: No separate retrieval step during inference (unless you still want it). |
| **Cons** | • **Retrieval quality matters**: Bad or missing passages can degrade answers.<br>• **Complex pipeline**: Requires a robust indexing/search system and a mechanism to fuse evidence.<br>• **Potential hallucination**: The model may still hallucinate if it mis‑weights the retrieved context. | • **Data‑hungry**: Requires a sizable, high‑quality dataset for effective adaptation.<br>• **Compute & time**: Fine‑tuning large models can be expensive and slow.<br>• **Stale knowledge**: Once trained, the model’s knowledge is frozen until you fine‑tune again. |
| **Typical use‑cases** | • Question‑answering over a constantly evolving medical guideline database.<br>• Customer support bots that need to reference the latest product catalog.<br>• Knowledge‑intensive applications where you want to show the source material. | • Clinical decision support that must follow a specific protocol (e.g., a set of diagnostic rules).<br>• Custom chatbots for a particular organization’s internal policies.<br>• Any scenario where you have a well‑defined, static training set. |
| **Hybrid approaches** | You can combine both: fine‑tune a base model on domain‑specific text, then augment it with a retrieval system to keep it current. This gives you the best of both worlds—internalized patterns plus up‑to‑date evidence. |

### Bottom line

* **Fine‑Tuning** rewrites the model’s knowledge by training it on new data. It’s powerful but costly and inflexible once the model is frozen.
* **RAG** keeps the model’s core weights intact and adds a dynamic “lookup” step, letting you pull in fresh information on demand without retraining.

Choosing between them depends on your constraints: data availability, update frequency, latency, and the need for explainability. In many real‑world settings, a hybrid of both yields the most robust solution.
------------------------------------------------------------
Query: What is an embedding?
Response: **Embeddings** are a way of turning complex, often high‑dimensional or categorical data into a compact, continuous vector representation that a machine learning model can work with.

### Core idea
- **Map to a vector space**: Each item (word, image, patient record, etc.) is represented as a numeric vector (e.g., `[0.12, -0.45, 0.78, …]`).
- **Preserve meaning**: Similar items end up with vectors that are close together, while dissimilar items are far apart. This is usually achieved through training on a large dataset.

### Typical use‑cases

| Domain | What’s embedded | Why it helps |
|--------|-----------------|--------------|
| Natural language | Words, sub‑phrases, sentences | Allows models to capture semantic relationships (e.g., “king” – “man” + “woman” ≈ “queen”). |
| Computer vision | Images or image patches | Enables similarity search, clustering, or feeding into downstream classifiers. |
| Recommender systems | Users, items | Captures latent preferences and item characteristics for better recommendations. |
| Healthcare | Patient records, medical codes | Encodes complex clinical information into a format that can be fed into predictive models (e.g., risk scoring, phenotyping). |

### How they’re created

1. **Pre‑training** – e.g., Word2Vec, GloVe, BERT, or transformer‑based models learn embeddings by predicting context or reconstructing input.
2. **Fine‑tuning** – Adjust embeddings on a specific downstream task (e.g., clinical outcome prediction).
3. **Explicit encoding** – One‑hot vectors or binary indicators can be transformed into dense embeddings via neural layers.

### Key properties

- **Dimensionality reduction**: A 50‑dimensional embedding can capture the essential information that might otherwise require thousands of features.
- **Generalization**: Models can handle unseen or rare items because embeddings capture underlying patterns.
- **Similarity metrics**: Cosine similarity, Euclidean distance, etc., can be used to quantify how alike two vectors are.

### Example in a hospital setting

A patient’s ICD‑10 diagnosis codes can be turned into an embedding that represents the overall disease profile. A machine learning model can then use that embedding to predict future hospitalization risk, readmission likelihood, or recommend personalized care plans.

---

In short, **an embedding is a learned numeric representation that condenses complex data into a vector space, preserving relationships and enabling efficient computation in machine learning pipelines.**
------------------------------------------------------------
Query: What is cosine similarity?
Response: **Cosine similarity** is a measure of similarity between two non‑zero vectors of an inner product space.
It is defined as the cosine of the angle between the two vectors, which ranges from –1 to 1:

\[
\text{cosine similarity}(A,B)=\frac{A\cdot B}{\|A\|\;\|B\|}
\]

where

* \(A \cdot B\) is the dot product of the vectors,
* \(\|A\|\) and \(\|B\|\) are the Euclidean norms (lengths) of the vectors.

---

### Why it’s useful

1. **Scale‑invariant** – It cares only about the *direction* of the vectors, not their magnitude.
2. **Common in text mining** – When documents are represented as term‑frequency or TF‑IDF vectors, cosine similarity tells how similar the documents’ content is.
3. **Used in recommendation systems, clustering, and information retrieval** – e.g., to find users with similar preferences or items with similar attributes.

### Intuition

* If the vectors point in the same direction, the angle is 0°, cosine is **1** (maximum similarity).
* If they are orthogonal (no shared components), the angle is 90°, cosine is **0** (no similarity).
* If they point in opposite directions, the angle is 180°, cosine is **–1** (maximum dissimilarity).

### Quick example

Suppose we have two 3‑dimensional vectors:

\(A = [1, 2, 3]\)
\(B = [4, 5, 6]\)

Dot product: \(A \cdot B = 1\cdot4 + 2\cdot5 + 3\cdot6 = 32\)

Norms: \(\|A\| = \sqrt{1^2+2^2+3^2} = \sqrt{14}\),
\(\|B\| = \sqrt{4^2+5^2+6^2} = \sqrt{77}\)

Cosine similarity: \(32 / (\sqrt{14}\sqrt{77}) \approx 0.974\).
The vectors are highly aligned.

---

If you need more specifics (e.g., implementation details or use in a particular domain like medical imaging or patient record similarity), let me know!
------------------------------------------------------------

#### ***Missing Information***

In [155]:
missing_queries = [
    "What is the cardiologist's phone number?",
    "What is the hospital's email address?",
    "Who is the head of the Cardiology Department?"
]
for query in missing_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What is the cardiologist's phone number?

--- Document 1 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.

--- Document 2 ---
## Important Note

This is fictional hospital information created for a LangChain RAG project. It is not clinical guidance.

--- Document 3 ---
## Outpatient Department

The Outpatient Department operates from 9:00 AM to 1:00 PM, Monday through Saturday.

## Visitor Guidelines

- Visitors should follow hospital staff instructions.
- Visiting conditions may be changed for operational or safety reasons.
- Visitors should avoid disturbing patients or clinical activities.

## Important Note

--- Document 4 ---
## General Ward

Visitors may visit patients in the General Ward during the scheduled visiting periods.

## Intensive Care Unit (ICU)

ICU visiting is restricted to the scheduled period. Visitors should follow instructions provided by hospital staff.

## Pediatrics

Pediatric department visiting hours are scheduled from 4:00 PM to 6:00 PM, Monday through Saturday.

## Outpatient Department
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: I’m sorry, but I couldn’t find a specific phone number for a cardiologist in the information I have. Could you let me know the cardiologist’s name or the hospital department you’re referring to? That way I can look up the correct contact details for you.
------------------------------------------------------------
Query: What is the hospital's email address?

--- Document 1 ---
## Important Note

This is fictional hospital information created for a LangChain RAG project. It is not clinical guidance.

--- Document 2 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.

--- Document 3 ---
# ABC General Hospital — Hospital Information

## Overview

ABC General Hospital is a fictional hospital created for the Hospital RAG learning project. The hospital provides outpatient, inpatient, emergency, diagnostic, and specialist services.

## Services

The hospital provides:

--- Document 4 ---
## Diagnostic Services

The hospital provides laboratory testing and diagnostic imaging. Availability of a particular test depends on the department and clinical requirement.

## Pharmacy

The hospital pharmacy provides prescribed medications during its operating hours. Medication availability may vary.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: I’m sorry, but I couldn’t locate the hospital’s email address in the knowledge base. If you have a specific department or contact in mind, let me know and I’ll try to find that information for you.
------------------------------------------------------------
Query: Who is the head of the Cardiology Department?

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
## Important Note

These visiting hours are fictional and created for RAG experimentation. They are not the schedule of a real hospital.
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: I’m sorry, but I don’t have that information in the system right now. If you can provide more context or specify a particular hospital or location, I’ll try again!
------------------------------------------------------------

#### ***Mixed Query***

In [156]:
mixed_queries = [
    "What services are available in the Cardiology Department, and what is the gender of patient cc3eac4a-34a7-9a15-1522-8087135631b7?"
]
for query in mixed_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What services are available in the Cardiology Department, and what is the gender of patient cc3eac4a-34a7-9a15-1522-8087135631b7?
Tool Name: name='search_patient' description="Search the hospital's synthetic patient records using a patient ID\n     and return the matching patient information." args_schema=<class 'langchain_core.utils.pydantic.search_patient'> func=<function search_patient at 0x000001D2F1182D40>

--- Document 1 ---
## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions.

## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions.

## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures.

--- Document 2 ---
| Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |

--- Document 3 ---
# ABC General Hospital — Departments

## Department Overview

ABC General Hospital has several clinical departments. | Department | Main Area | Typical Services |
|---|---|---|
| Cardiology | Heart and cardiovascular system | Cardiac evaluation and cardiovascular care |
| Neurology | Brain and nervous system | Neurological evaluation and care |
| Orthopedics | Bones, joints, and muscles | Musculoskeletal evaluation and treatment |
| Pediatrics | Children and adolescents | Pediatric consultations and care |
| Dermatology | Skin, hair, and nails | Dermatological evaluation and care |
| General Medicine | General adult healthcare | General medical evaluation and management |

## Cardiology

The Cardiology Department focuses on evaluation and management of cardiovascular conditions. ## Neurology

The Neurology Department focuses on conditions involving the brain, spinal cord, nerves, and related neurological functions. ## Orthopedics

The Orthopedics Department focuses on musculoskeletal conditions involving bones, joints, muscles, ligaments, and related structures. ## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents. ## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails. ## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients. ## Important Note

This is fictional hospital information created for a LangChain RAG project.

--- Document 4 ---
## Services

The hospital provides:

- Outpatient consultations
- Inpatient care
- Emergency services
- Diagnostic laboratory services
- Radiology and imaging
- Pharmacy services
- Physiotherapy
- Preventive health consultations

## Emergency Services

The Emergency Department operates 24 hours a day, 7 days a week.

--- Document 5 ---
## Pediatrics

The Pediatrics Department provides healthcare services for children and adolescents.

## Dermatology

The Dermatology Department focuses on conditions affecting the skin, hair, and nails.

## General Medicine

The General Medicine Department provides general medical evaluation and management for adult patients.

## Important Note
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1182B60>
Response: **Cardiology Department Services**
- Cardiac evaluation
- Cardiovascular care

**Patient Information**
- Patient ID: cc3eac4a‑34a7‑9a15‑1522‑8087135631b7
- Gender: **Male** (M)
------------------------------------------------------------

#### ***Evaluation Dataset***

In [206]:
test_queries = [
    "What services are available in the Cardiology Department?",
    "What diagnostic services are available at the hospital?",
    "What is the cardiologist's phone number?"
]

for query in test_queries:
    print("Query:", query)
    print("Response:", tool_loop_execution(query).content)
    print("-" * 60)

Query: What services are available in the Cardiology Department?
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1180400>
Response: **Cardiology Department – Available Services**

| Service | Brief Description |
|---------|-------------------|
| **Cardiac Evaluation & Cardiovascular Care** | Comprehensive assessment and ongoing management of all heart‑related conditions. |
| **Diagnostic Testing** | Includes ECG, Holter monitoring, stress testing, echocardiography, and cardiac imaging to evaluate heart structure and function. |
| **Interventional Cardiology** | Percutaneous coronary interventions (PCI), angioplasty, stent placement, and related catheter‑based procedures. |
| **Electrophysiology** | Arrhythmia evaluation and treatment, including pacemaker and defibrillator implantation. |
| **Heart Failure Management** | Specialized care for patients with heart failure, including medication optimization and device therapy. |
| **Pre‑operative Cardiac Assessment** | Evaluation of cardiac risk before non‑cardiac surgery. |
| **Lifestyle & Rehabilitation Programs** | Cardiac rehab, diet counseling, and exercise prescription to support long‑term heart health. |

These services are designed to provide a full spectrum of care—from initial evaluation through advanced interventions and long‑term management—for patients with cardiovascular conditions. If you’d like details on a specific service or procedure, let me know!
------------------------------------------------------------
Query: What diagnostic services are available at the hospital?
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1180400>
Response: **Diagnostic services available at the hospital**

| Category | Services | Key features |
|----------|----------|--------------|
| **Laboratory testing** | • Routine blood counts, chemistry panels, urinalysis, and coagulation studies<br>• Specialized tests (e.g., microbiology, histopathology, molecular diagnostics)<br>• On‑site pathology and cytology labs with 24/7 turnaround for critical results | • Accredited CLIA‑certified lab<br>• Rapid reporting via electronic health record (EHR) |
| **Radiology / Imaging** | • **X‑ray** (plain film, portable, orthopedics)<br>• **Computed Tomography (CT)** – diagnostic and interventional<br>• **Magnetic Resonance Imaging (MRI)** – brain, spine, musculoskeletal, vascular<br>• **Ultrasound** – abdominal, obstetric, vascular, echocardiography<br>• **Nuclear Medicine** – bone scans, PET/CT<br>• **Mammography** – screening and diagnostic<br>• **Radiation therapy imaging** (for planning) | • 24/7 imaging suite with PACS integration<br>• Dedicated radiology department staffed by board‑certified radiologists |

These services are provided through the hospital’s Diagnostic Laboratory and Radiology & Imaging Departments, ensuring timely and accurate results to support patient care.
------------------------------------------------------------
Query: What is the cardiologist's phone number?
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1180400>
Tool Name: name='hospital_search' description='Search the hospital knowledge base and answer questions using information retrieved from the hospital documents.' args_schema=<class 'langchain_core.utils.pydantic.hospital_search'> func=<function hospital_search at 0x000001D2F1180400>
Response: I’m sorry, but I don’t have that information in the current data set. If you have a specific cardiologist’s name or a department you’re trying to reach, let me know and I’ll see if I can help locate the correct contact details.
------------------------------------------------------------